<template><div><h1 id="api" tabindex="-1"><a class="header-anchor" href="#api"><span>api</span></a></h1>
<h2 id="f12打开的api" tabindex="-1"><a class="header-anchor" href="#f12打开的api"><span>f12打开的api</span></a></h2>
<p>&quot;API&quot; 是 &quot;Application Programming Interface&quot; 的缩写。它是一组定义软件组件之间交互的规则和工具。API 可以用于不同软件之间的通信，允许它们共享数据和功能。API 提供了一种标准的方式，使得开发者可以访问某个软件或服务的功能，而无需深入了解其内部工作原理。</p>
<p>在软件开发中，API 可以是用于与操作系统、库、框架或其他服务进行交互的一组规范。API 可以采用不同的形式，包括库函数、协议、工具等。通常，API 提供了一组定义良好的接口，开发者可以使用这些接口进行编程，而无需了解底层的实现细节。
打开的api</p>
<p>&quot;API&quot; 是 &quot;Application Programming Interface&quot; 的缩写。它是一组定义软件组件之间交互的规则和工具。API 可以用于不同软件之间的通信，允许它们共享数据和功能。API 提供了一种标准的方式，使得开发者可以访问某个软件或服务的功能，而无需深入了解其内部工作原理。</p>
<p>在软件开发中，API 可以是用于与操作系统、库、框架或其他服务进行交互的一组规范。API 可以采用不同的形式，包括库函数、协议、工具等。通常，API 提供了一组定义良好的接口，开发者可以使用这些接口进行编程，而无需了解底层的实现细节。
以下是一些非常简单的 API 请求的例子，你可以通过浏览器的开发者工具的控制台来执行它们：</p>
<ol>
<li>
<p><strong>获取当前时间的 API 请求：</strong></p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token function">fetch</span><span class="token punctuation">(</span><span class="token string">'https://worldtimeapi.org/api/ip'</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">response</span> <span class="token operator">=></span> response<span class="token punctuation">.</span><span class="token function">json</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">data</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'Current Time:'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>utc_datetime<span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token parameter">error</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Error fetching time:'</span><span class="token punctuation">,</span> error<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p><strong>获取随机名言的 API 请求：</strong></p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token function">fetch</span><span class="token punctuation">(</span><span class="token string">'https://api.quotable.io/random'</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">response</span> <span class="token operator">=></span> response<span class="token punctuation">.</span><span class="token function">json</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">data</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'Random Quote:'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>content<span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token parameter">error</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Error fetching quote:'</span><span class="token punctuation">,</span> error<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p><strong>获取当前城市天气的 API 请求（需要替换城市名）：</strong></p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> cityName <span class="token operator">=</span> <span class="token string">'London'</span><span class="token punctuation">;</span> <span class="token comment">// 替换成你想查询的城市名</span>
<span class="token function">fetch</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://api.openweathermap.org/data/2.5/weather?q=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>cityName<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">&amp;appid=YOUR_API_KEY</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">response</span> <span class="token operator">=></span> response<span class="token punctuation">.</span><span class="token function">json</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">data</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'Weather in'</span><span class="token punctuation">,</span> cityName <span class="token operator">+</span> <span class="token string">':'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>weather<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>description<span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token parameter">error</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Error fetching weather:'</span><span class="token punctuation">,</span> error<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
</ol>
<p>请注意，这些例子中使用的 API 地址和密钥可能需要根据具体情况进行替换。确保你有权访问这些 API，并在代码中使用正确的地址和密钥。</p>
</div></template>


